### ISSUE TITLE
`router`: A way to prevent `replaceState` and `pushState`

### ISSUE THREAD

**Issue by silverwind** [Lusito/react-nano#3]
To implement navigation warnings like "Are you sure to leave this unsaved page?" it would be nice if there were a way to prevent [`replaceState` and `pushState`](https://github.com/Lusito/react-nano/blob/3efa0ac8503688c2796a19504e07dd57eef2da18/packages/router/src/history.ts#L21-L30), ideally in a async fashing.

How about adding a `shouldAbortNavigation` option to the `Router` that accepts a function that, if present, is awaited and if it returns `true`, abort the navigation?

**Comment by Lusito** [comment]
Hi @silverwind, sorry for the delay. Life kept me very busy.

Sounds like a valid request. Would this API work?

```tsx
<Router onNavigate={onNavigate} ...>
```
with:
```ts
export type OnNavigateData = {
    from: string;
    to: string;
    type: "push" | "replace";
};
export type OnNavigateFn = (data: OnNavigateData) => Promise<boolean>;

export interface RouterHistory {
    push: (path: string) => Promise<boolean>;
    replace: (path: string) => Promise<boolean>;
}

export interface RouterProps {
    ....
    /**
     * An async callback that will be called on a navigation event.
     * If it resolves to false, the navigation event will be aborted
     */
    onNavigate?: OnNavigateFn;
}
```

**Comment by silverwind** [comment]
Sounds good. I would change the return type to accept both sync and async:

````ts
export type OnNavigateFn = (data: OnNavigateData) => Promise<boolean> | boolean;
````

Implementation should be the same, you just `await onNavigateFn`.

**Comment by Lusito** [comment]
A new version has been released.
